version: '3.7'

services:
  nginx:
    restart: ${RESTART}
    build:
      context: ../../images/nginx
      args:
        NGINX_ROOT_PATH: ${NGINX_ROOT_PATH}
        PHP_FPM_HOST: ${PROJECT_NAME}-${PHP_FPM_CONTAINER_NAME}
    container_name: ${PROJECT_NAME}-${NGINX_CONTAINER_NAME}
    hostname: ${PROJECT_NAME}-${NGINX_CONTAINER_NAME}-${ENVIRONMENT}
    depends_on:
      - php_fpm
    ports:
      - ${NGINX_PORT_80}:80
    volumes:
      - ${VOLUME_APPLICATION}:${APPLICATION_ROOT_PATH}/:ro
      - ${VOLUME_NGINX_LOGS}:/var/log/nginx/:rw
  php_fpm:
    restart: ${RESTART}
    build:
      context: ../../images/php_fpm
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        APPLICATION_ROOT_PATH: ${APPLICATION_ROOT_PATH}
    container_name: ${PROJECT_NAME}-${PHP_FPM_CONTAINER_NAME}
    hostname: ${PROJECT_NAME}-${PHP_FPM_CONTAINER_NAME}-${ENVIRONMENT}
    volumes:
      - ${VOLUME_APPLICATION}:${APPLICATION_ROOT_PATH}/:rw
  mysql:
    restart: ${RESTART}
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-${MYSQL_CONTAINER_NAME}
    volumes:
      - ${VOLUME_MYSQL}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  pma:
    restart: ${RESTART}
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-${PMA_CONTAINER_NAME}
    depends_on:
      - mysql
    ports:
      - ${PMA_PORT_80}:80
    environment:
      PMA_HOST: ${PROJECT_NAME}-${MYSQL_CONTAINER_NAME}